export const adminMockDb = {
  dashboard_stats: {
    total_students: 2451,
    total_students_change: '+3.2% vs last term',
    total_staff: 184,
    staff_change: 'No change',
    term_revenue: 1200000,
    revenue_change: '+8.4% YoY',
    revenue_collected_pct: 75,
    attendance_today: 96.8,
    attendance_change: '-0.5% vs yesterday',
    absent_count: 12,
    late_count: 4,
  },
  dashboard_activities: [
    { id: 1, type: 'payment', title: 'Term Fee Payment Received', desc: 'Payment of $4,500 recorded for Student ID: 10452 (Grade 10).', time: '10 mins ago' },
    { id: 2, type: 'admission', title: 'New Admission Application', desc: 'Application #A-2025-089 submitted for Grade 5. Pending review.', time: '1 hour ago' },
    { id: 3, type: 'meeting', title: 'Staff Meeting Scheduled', desc: 'Principal called for a general staff meeting on Friday at 3:00 PM.', time: '3 hours ago' },
    { id: 4, type: 'system', title: 'System Maintenance Alert', desc: 'Scheduled portal downtime this Sunday from 02:00 AM to 04:00 AM.', time: 'Yesterday' },
    { id: 5, type: 'admission', title: 'Admission Interview Scheduled', desc: 'Interview for Grade 1 applicant (Olayinka S.) set for Monday.', time: 'Yesterday' },
    { id: 6, type: 'payment', title: 'Bulk Uniform Purchase', desc: 'Inventory restock: 200 units of primary school blazers purchased.', time: '2 days ago' },
    { id: 7, type: 'meeting', title: 'PTA Executive Meeting', desc: 'Discussion on the upcoming Sports Day logistics and security.', time: '2 days ago' },
    { id: 8, type: 'system', title: 'Database Backup Completed', desc: 'Weekly automated backup of student records successfully stored.', time: '3 days ago' },
  ],
  academic_classes: [
    { id: 'c10', name: 'Class 10' },
    { id: 'c11', name: 'Class 11' },
    { id: 'c12', name: 'Class 12' },
  ],
  academic_sections: [
    { id: 's10a', class_id: 'c10', name: 'Section A' },
    { id: 's10b', class_id: 'c10', name: 'Section B' },
    { id: 's11a', class_id: 'c11', name: 'Section A' },
    { id: 's12a', class_id: 'c12', name: 'Section A' },
  ],
  teachers: [
    { id: 't1', name: 'Dr. Robert Chen' },
    { id: 't2', name: 'Sarah Jenkins' },
    { id: 't3', name: 'Prof. Alan Smith' },
    { id: 't4', name: 'Emma Watson' },
    { id: 't5', name: 'John Doe' },
    { id: 't6', name: 'Maria Garcia' },
  ],
  subjects: [
    { id: 's1', code: 'MAT101', type: 'Core', name: 'Advanced Mathematics', teacher: 'Dr. Robert Chen', max_marks: '100 (Theory) / 50 (Practical)' },
    { id: 's2', code: 'PHY101', type: 'Core', name: 'Physics Fundamentals', teacher: 'Sarah Jenkins', max_marks: '100 (Theory)' },
    { id: 's3', code: 'ENG102', type: 'Language', name: 'English Literature', teacher: 'Prof. Alan Smith', max_marks: '100 (Theory)' },
  ],
  students: [
    { id: '10001', name: 'Eleanor Vance', grade: 'Grade 12', section: 'Section A', admission_no: 'ADM-2023-001', parent: 'Mr. & Mrs. Vance', email: 'e.vance@example.com', phone: '+234 801 111 2222', address: '12 Oak Street, Lagos', gender: 'Female', dob: 'May 12, 2008', status: 'Active', avatar: '' },
    { id: '10002', name: 'Luke Crain', grade: 'Grade 11', section: 'Section B', admission_no: 'ADM-2023-002', parent: 'Mr. Stephen Crain', email: 'l.crain@example.com', phone: '+234 802 222 3333', address: '45 Hill House, Lagos', gender: 'Male', dob: 'Oct 05, 2009', status: 'Active', avatar: '' },
    { id: '10003', name: 'Shirley Crain', grade: 'Grade 12', section: 'Section A', admission_no: 'ADM-2022-045', parent: 'Mr. Stephen Crain', email: 's.crain@example.com', phone: '+234 803 333 4444', address: '22 Mortuary Road, Lagos', gender: 'Female', dob: 'Mar 20, 2008', status: 'Active', avatar: '' },
    { id: '10004', name: 'Theodora Crain', grade: 'Grade 10', section: 'Section A', admission_no: 'ADM-2024-012', parent: 'Mr. Stephen Crain', email: 't.crain@example.com', phone: '+234 804 444 5555', address: '88 Blue Lane, Lagos', gender: 'Female', dob: 'Aug 15, 2010', status: 'Active', avatar: '' },
    { id: '10005', name: 'Steven Crain', grade: 'Grade 9', section: 'Section B', admission_no: 'ADM-2024-089', parent: 'Mr. Stephen Crain', email: 'st.crain@example.com', phone: '+234 805 555 6666', address: "10 Writer's Block, Lagos", gender: 'Male', dob: 'Feb 10, 2011', status: 'Inactive', avatar: '' },
  ],
  staff_members: [
    { id: '1', name: 'Dr. Sarah Jenkins', role: 'Head of Mathematics', department: 'Mathematics Dept.', email: 's.jenkins@edumanage.edu', phone: '+234 801 234 5678', address: '12 Victoria Island, Lagos', joinDate: 'Sept 12, 2018', status: 'Active', avatar: null },
    { id: '2', name: 'Prof. Robert Chen', role: 'Senior Lecturer', department: 'Physics Dept.', email: 'r.chen@edumanage.edu', phone: '+234 802 345 6789', address: '45 Lekki Phase 1, Lagos', joinDate: 'Jan 05, 2020', status: 'Active', avatar: null },
    { id: '3', name: 'Elena Rostova', role: 'Academic Coordinator', department: 'Administration', email: 'e.rostova@edumanage.edu', phone: '+234 803 456 7890', address: '22 Ikeja GRA, Lagos', joinDate: 'Mar 20, 2021', status: 'On Leave', avatar: null },
    { id: '4', name: 'David Kim', role: 'Adjunct Professor', department: 'Humanities Dept.', email: 'd.kim@edumanage.edu', phone: '+234 804 567 8901', address: 'Surulere, Lagos', joinDate: 'Aug 15, 2022', status: 'Active', avatar: null },
    { id: '5', name: 'Prof. Alan Smith', role: 'Senior Lecturer', department: 'English Dept.', email: 'a.smith@edumanage.edu', phone: '+234 805 678 9012', address: 'Yaba, Lagos', joinDate: 'Feb 10, 2019', status: 'Active', avatar: null },
    { id: '6', name: 'Dr. Maria Santos', role: 'Lab Instructor', department: 'Science Dept.', email: 'm.santos@edumanage.edu', phone: '+234 806 789 0123', address: 'Maryland, Lagos', joinDate: 'Nov 22, 2023', status: 'Active', avatar: null },
    { id: '7', name: 'James Wilson', role: 'History Teacher', department: 'Humanities Dept.', email: 'j.wilson@edumanage.edu', phone: '+234 807 890 1234', address: 'Gbagada, Lagos', joinDate: 'Oct 01, 2021', status: 'Active', avatar: null },
    { id: '8', name: 'Linda Garcia', role: 'Biology Teacher', department: 'Science Dept.', email: 'l.garcia@edumanage.edu', phone: '+234 808 901 2345', address: 'Apapa, Lagos', joinDate: 'Jan 15, 2024', status: 'Active', avatar: null },
    { id: '9', name: 'Michael Brown', role: 'Chemistry Teacher', department: 'Science Dept.', email: 'm.brown@edumanage.edu', phone: '+234 809 012 3456', address: 'Festac, Lagos', joinDate: 'Sept 30, 2022', status: 'Active', avatar: null },
    { id: '10', name: 'Susan Taylor', role: 'Art Instructor', department: 'Arts Dept.', email: 's.taylor@edumanage.edu', phone: '+234 810 123 4567', address: 'Ikoyi, Lagos', joinDate: 'May 05, 2020', status: 'Active', avatar: null },
    { id: '11', name: 'Christopher Lee', role: 'Music Teacher', department: 'Arts Dept.', email: 'c.lee@edumanage.edu', phone: '+234 811 234 5678', address: 'Ajah, Lagos', joinDate: 'July 12, 2021', status: 'Active', avatar: null },
    { id: '12', name: 'Jessica Davis', role: 'Physical Education', department: 'Sports Dept.', email: 'j.davis@edumanage.edu', phone: '+234 812 345 6789', address: 'Epe, Lagos', joinDate: 'Dec 18, 2018', status: 'Active', avatar: null },
    { id: '13', name: 'Matthew Moore', role: 'IT Specialist', department: 'Administration', email: 'm.moore@edumanage.edu', phone: '+234 813 456 7890', address: 'Ogba, Lagos', joinDate: 'April 22, 2023', status: 'Active', avatar: null },
    { id: '14', name: 'Karen White', role: 'Librarian', department: 'Library', email: 'k.white@edumanage.edu', phone: '+234 814 567 8901', address: 'Mushin, Lagos', joinDate: 'Aug 08, 2020', status: 'Active', avatar: null },
    { id: '15', name: 'Paul Anderson', role: 'Security Head', department: 'Security', email: 'p.anderson@edumanage.edu', phone: '+234 815 678 9012', address: 'Agege, Lagos', joinDate: 'Feb 14, 2019', status: 'Active', avatar: null },
  ],
  attendance_summaries: [
    { id: 1, grade: 'Grade 10', section: 'Science', subject: 'Advanced Physics', date: 'May 20, 2026', present: 42, absent: 3, percentage: 93 },
    { id: 2, grade: 'Grade 11', section: 'Arts', subject: 'History', date: 'May 20, 2026', present: 38, absent: 2, percentage: 95 },
    { id: 3, grade: 'Grade 12', section: 'Science', subject: 'Calculus', date: 'May 19, 2026', present: 25, absent: 5, percentage: 83 },
  ],
  inventory_items: [
    { id: 'INV-1042', name: 'Advanced Physics Textbook', category: 'Books & Media', stock: 145, reorder: 50, status: 'Optimal' },
    { id: 'INV-2091', name: 'Student Desks (Standard)', category: 'Furniture', stock: 12, reorder: 20, status: 'Low Stock' },
    { id: 'INV-3015', name: 'Beaker Set 500ml', category: 'Lab Equipment', stock: 88, reorder: 30, status: 'Optimal' },
    { id: 'INV-4402', name: 'Dry Erase Markers (Pack)', category: 'Stationary', stock: 5, reorder: 25, status: 'Low Stock' },
    { id: 'INV-5110', name: 'Chromebook Pro', category: 'IT & Electronics', stock: 42, reorder: 10, status: 'Optimal' },
  ],
  fee_types: [
    { id: 1, name: 'Tuition Fee', grade: 'Grade 10', amount: 3500, status: 'Active' },
    { id: 2, name: 'Textbooks & Workbooks', grade: 'Grade 10', amount: 450, status: 'Active' },
    { id: 3, name: 'Science Laboratory Fee', grade: 'Grade 10', amount: 200, status: 'Active' },
    { id: 4, name: 'Computer & IT Levy', grade: 'Grade 10', amount: 150, status: 'Active' },
    { id: 5, name: 'School Uniform Set', grade: 'Grade 10', amount: 300, status: 'Active' },
    { id: 6, name: 'Tuition Fee', grade: 'Grade 11', amount: 4000, status: 'Active' },
    { id: 7, name: 'Textbooks & Workbooks', grade: 'Grade 11', amount: 500, status: 'Active' },
    { id: 8, name: 'Science Laboratory Fee', grade: 'Grade 11', amount: 250, status: 'Pending' },
    { id: 9, name: 'Computer & IT Levy', grade: 'Grade 11', amount: 150, status: 'Active' },
    { id: 10, name: 'Extracurricular Activities', grade: 'Grade 11', amount: 200, status: 'Active' },
    { id: 11, name: 'Tuition Fee', grade: 'Grade 12', amount: 4500, status: 'Active' },
    { id: 12, name: 'Textbooks & Workbooks', grade: 'Grade 12', amount: 550, status: 'Active' },
    { id: 13, name: 'Graduation & Alumni Fee', grade: 'Grade 12', amount: 600, status: 'Overdue' },
    { id: 14, name: 'Career Guidance Levy', grade: 'Grade 12', amount: 100, status: 'Active' },
    { id: 15, name: 'Examination Council Fee', grade: 'Grade 12', amount: 300, status: 'Active' },
    { id: 16, name: 'Tuition Fee', grade: 'Grade 9', amount: 3000, status: 'Active' },
    { id: 17, name: 'Orientation Package', grade: 'Grade 9', amount: 200, status: 'Active' },
    { id: 18, name: 'Textbooks & Workbooks', grade: 'Grade 9', amount: 400, status: 'Active' },
    { id: 19, name: 'General Materials Fee', grade: 'Grade 9', amount: 100, status: 'Active' },
    { id: 20, name: 'Transportation (Bus Route A)', grade: 'All Grades', amount: 800, status: 'Active' },
    { id: 21, name: 'Library Late Fees', grade: 'Various', amount: 45, status: 'Overdue' },
  ],
  fee_transactions: [
    { id: 1, student: 'Alice Johnson', amount: 4500, method: 'Card ends *4211', desc: 'Tuition - ID #8472', time: 'Today, 09:41 AM', color: '#C9A020' },
    { id: 2, student: 'Michael Smith', amount: 800, method: 'Bank Transfer', desc: 'Transport Fee - ID #9921', time: 'Yesterday, 14:22 PM', color: '#6B6660' },
    { id: 3, student: 'Emma Davis', amount: 350, method: 'Cash', desc: 'Lab Fee - ID #7364', time: 'Oct 24, 11:05 AM', color: '#6B6660' },
    { id: 4, student: 'System Auto-Billed', amount: 135, method: 'Automated', desc: 'Late Penalty Applied (3 Accounts)', time: 'Oct 23, 00:00 AM', color: '#EF4444' },
    { id: 5, student: 'David Wilson', amount: 1200, method: 'Bank Transfer', desc: 'Graduation Fee - ID #1023', time: 'Oct 22, 10:15 AM', color: '#C9A020' },
    { id: 6, student: 'Sarah Parker', amount: 300, method: 'Card ends *1189', desc: 'Uniform - ID #5542', time: 'Oct 21, 09:30 AM', color: '#6B6660' },
    { id: 7, student: 'James Brown', amount: 150, method: 'Cash', desc: 'Robotics Fee - ID #2291', time: 'Oct 20, 16:45 PM', color: '#6B6660' },
    { id: 8, student: 'Linda Garcia', amount: 5000, method: 'Bank Transfer', desc: 'Tuition - ID #8871', time: 'Oct 19, 11:20 AM', color: '#C9A020' },
  ],
  admissions_applications: [
    { id: 'APP-25-001', student_name: 'Eleanor Vance', program: 'Computer Science', date_applied: 'Oct 12, 2024', status: 'Admitted' },
    { id: 'APP-25-002', student_name: 'Theodore Crain', program: 'Business Admin', date_applied: 'Oct 14, 2024', status: 'Pending Review' },
    { id: 'APP-25-003', student_name: 'Shirley Jackson', program: 'Literature', date_applied: 'Oct 15, 2024', status: 'Under Evaluation' },
    { id: 'APP-25-004', student_name: 'Luke Crain', program: 'Engineering', date_applied: 'Oct 18, 2024', status: 'Admitted' },
    { id: 'APP-25-005', student_name: 'Steven Crain', program: 'Architecture', date_applied: 'Oct 20, 2024', status: 'Rejected' },
  ],
  settings_classes: [
    { id: '1', level: 'Nursery', sections: 'A, B', capacity_used: 40, capacity_total: 50, lead_faculty: 'Sarah Jenkins' },
    { id: '2', level: 'Grade 1', sections: 'A, B, C', capacity_used: 85, capacity_total: 90, lead_faculty: 'Michael Chen' },
    { id: '3', level: 'Grade 10', sections: 'Science, Arts', capacity_used: 110, capacity_total: 120, lead_faculty: 'Dr. Robert Vance' },
  ],
  academic_terms: [
    { id: '1', name: 'Fall Term 2023', start: 'Sept 1', end: 'Dec 15', weeks: 14, status: 'Active' },
    { id: '2', name: 'Spring Term 2024', start: 'Jan 10', end: 'May 20', weeks: 18, status: 'Upcoming' },
  ],
  notices: [
    { id: '1', title: 'Emergency Weather Protocol', audience: 'ALL STAFF & STUDENTS', body: 'Please review the updated winter weather protocols. In case of heavy snow, school…', date: 'Today', highlight: true },
    { id: '2', title: 'Faculty Meeting Rescheduled', audience: 'FACULTY ONLY', body: 'The monthly departmental review has been moved from Tuesday to Thursday afterno…', date: 'Yesterday', highlight: false },
    { id: '3', title: 'End of Term Examinations Schedule', audience: 'GRADE 9-12', body: 'The preliminary schedule for the Fall term finals has been posted. Please ensure all…', date: 'Oct 12', highlight: false },
  ],
  messaging_inbox: [
    { id: '1', sender: 'Dr. Emily Chen', subject: 'Q3 Syllabus Updates Needed', preview: 'Please review the attached changes for t…', time: '09:42 AM', read: false, label: 'Faculty' },
    { id: '2', sender: 'Admissions Office', subject: 'Incoming Freshman Orientation', preview: "The schedule for next week's orientation i…", time: 'Yesterday', read: true, label: null },
    { id: '3', sender: 'Prof. Marcus Johnson', subject: 'Lab Equipment Requisition', preview: 'I have submitted the forms for the new mi…', time: 'Mon', read: true, label: 'Urgent' },
  ],
  messaging_message: {
    id: '2',
    sender: 'Admissions Office',
    senderEmail: 'admissions@edumanage.edu',
    to: 'admin@edumanage.edu',
    subject: 'Incoming Freshman Orientation',
    date: 'Oct 24, 2023, 2:30 PM',
    body: `Hello Administration Team,\n\nThe schedule for next week's incoming freshman orientation has been finalized and approved by the Dean's office. We are expecting approximately 450 new students to attend across the three-day event.\n\nKey highlights that require your attention:\n\n• The opening keynote is scheduled for Monday at 9:00 AM in the Main Auditorium. Please ensure AV setup is completed by 8:00 AM.\n\n• Registration packets are currently being assembled in Room 104 and will be ready for distribution on Sunday evening.\n\n• We need final confirmation on the departmental breakout room assignments. Please review the attached spreadsheet.\n\nLet's schedule a brief 15-minute sync call before the weekend to align on any last-minute logistics.`,
  },
  reports_enrollment: [
    { q: 'Q1', current: 1200, prev: 900 },
    { q: 'Q2', current: 1800, prev: 1400 },
    { q: 'Q3', current: 3200, prev: 2000 },
    { q: 'Q4', current: 3600, prev: 2400 },
  ],
  reports_top_performers: [
    { id: '1', name: 'Eleanor Vance', grade: 'Grade 12', score: 98.5, section: 'Section A' },
    { id: '2', name: 'Luke Crain', grade: 'Grade 11', score: 97.2, section: 'Section B' },
    { id: '3', name: 'Theodora Crain', grade: 'Grade 10', score: 96.8, section: 'Section A' },
    { id: '4', name: 'Shirley Crain', grade: 'Grade 12', score: 95.0, section: 'Section A' },
    { id: '5', name: 'Steven Crain', grade: 'Grade 9', score: 94.2, section: 'Section B' },
    { id: '6', name: 'Nell Crain', grade: 'Grade 10', score: 93.8, section: 'Section B' },
    { id: '7', name: 'Olivia Crain', grade: 'Grade 11', score: 92.5, section: 'Section A' },
    { id: '8', name: 'Hugh Crain', grade: 'Grade 12', score: 91.0, section: 'Section B' },
  ],
  results_assessments: [
    { id: '1', name: 'FIRST C. A', maxScore: 10 },
    { id: '2', name: 'SECOND C. A', maxScore: 10 },
    { id: '3', name: 'THIRD C. A', maxScore: 10 },
    { id: '4', name: 'EXAM', maxScore: 70 },
  ],
  results_grading_scale: [
    { id: '1', grade: 'A1', lower: 75, upper: 100, remark: 'EXCELLENT', color: '#C9A020' },
    { id: '2', grade: 'B2', lower: 70, upper: 74, remark: 'VERY GOOD', color: '#10B981' },
    { id: '3', grade: 'B3', lower: 65, upper: 69, remark: 'GOOD', color: '#3B82F6' },
    { id: '4', grade: 'C4', lower: 60, upper: 64, remark: 'CREDIT', color: '#8B5CF6' },
    { id: '5', grade: 'C5', lower: 55, upper: 59, remark: 'CREDIT', color: '#F59E0B' },
    { id: '6', grade: 'C6', lower: 50, upper: 54, remark: 'CREDIT', color: '#EF4444' },
    { id: '7', grade: 'F9', lower: 0, upper: 49, remark: 'FAIL', color: '#EF4444' },
  ],
} as const

export const adminMockViews = {
  dashboard: {
    stats: adminMockDb.dashboard_stats,
    activities: adminMockDb.dashboard_activities,
  },
  academics: {
    classes: adminMockDb.academic_classes.map(c => ({
      id: c.id,
      name: c.name,
      sections: adminMockDb.academic_sections.filter(s => s.class_id === c.id).map(s => ({ id: s.id, name: s.name })),
    })),
    subjects: adminMockDb.subjects,
    teachers: adminMockDb.teachers.map(t => t.name),
  },
  students: {
    students: adminMockDb.students,
  },
  staff: {
    members: adminMockDb.staff_members,
  },
  attendance: {
    summary: adminMockDb.attendance_summaries,
  },
  inventory: {
    total: 248,
    items: adminMockDb.inventory_items,
    staff: adminMockDb.teachers.map(t => t.name),
  },
  fee_management: {
    total_collected: 1245000,
    total_change: '+12% from last term',
    pending_clearance: 84500,
    pending_invoices: 42,
    overdue_fees: 12350,
    fee_types: adminMockDb.fee_types,
    recent_transactions: adminMockDb.fee_transactions,
  },
  admission: {
    data: adminMockDb.admissions_applications,
    total: 124,
    current_page: 1,
    last_page: 25,
  },
  settings: {
    classes: adminMockDb.settings_classes,
    staff: adminMockDb.teachers.map(t => t.name),
    terms: adminMockDb.academic_terms,
    notices: adminMockDb.notices,
  },
  messaging: {
    inbox: adminMockDb.messaging_inbox,
    message: adminMockDb.messaging_message,
  },
  reports: {
    enrollment: adminMockDb.reports_enrollment,
    fee_collected_pct: 82,
    top_performers: adminMockDb.reports_top_performers,
    student_staff_ratio: '1:24',
    attendance: { students: 94, faculty: 98, support: 92 },
  },
  results: {
    assessments: adminMockDb.results_assessments,
    grading_scale: adminMockDb.results_grading_scale,
  },
} as const
